# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

description: |
  Install/configure docker with buildx to
  cross-compile docker images and deploy them

jobs:
  buildx:
    working_directory: ~/docker-pdf2pptx
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install docker buildx
          command: |
            apk add --no-cache curl make
            mkdir -p ~/.docker/cli-plugins
            baseUrl="https://github.com/docker/buildx/releases/download"
            fileName="buildx-v<< parameters.version >>.linux-amd64"
            url="${baseUrl}/v<< parameters.version >>/${fileName}"
            curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            echo 'export DOCKER_CLI_EXPERIMENTAL="enabled"' >> $BASH_ENV
      - run:
          name: Prepare docker buildx
          command: |
            docker buildx install
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: make

workflows:
  buildx-and-push:
    jobs:
      - buildx:
          filters:
              tags:
                only: /.*/
