# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

description: |
  Install/configure docker with buildx to
  cross-compile docker images and deploy them

jobs:
  buildx:
    parameters:
      version:
        default: 0.5.1
        type: string
    working_directory: ~/docker-pdf2pptx
    docker:
      - image: drpsychick/dind-buildx:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Install make
          command: |
            apk add --no-cache make
      - run:
          name: Prepare Docker buildx
          command: |
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create xbuilder
            docker buildx create xbuilder --name xbuilder --use
            docker buildx inspect --bootstrap
      - run: make build

workflows:
  buildx-and-push:
    jobs:
      - buildx:
          filters:
              tags:
                only: /.*/
